Table:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    AttributeDefinitions:
      -
        AttributeName: eventId
        AttributeType: S
      -
        AttributeName: transactionType
        AttributeType: S
    KeySchema:
      -
        AttributeName: eventId
        KeyType: HASH
      -
        AttributeName: transactionType
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    TableName: StellarTransactions
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES