Table:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    AttributeDefinitions:
      -
        AttributeName: id
        AttributeType: S
      -
        AttributeName: status
        AttributeType: S
    KeySchema:
      -
        AttributeName: id
        KeyType: HASH
      -
        AttributeName: status
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    TableName: ToaEvents
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES